### ISSUE TITLE
WWTTF will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by snam24** [godbout/WooshyWindowToTheForeground#16]
the workflow doesn't work for some reason and there's a warning popup every time I try to 'ww' on alfred.

<img width="453" alt="Screenshot_2023-08-06-18_52_07_iX8tn0" src="https://github.com/godbout/WooshyWindowToTheForeground/assets/83625480/8ea2fc02-92d8-431c-b9c8-0809f6021894">

**Comment by jamie9090** [comment]
Same!

**Comment by jamie9090** [comment]
I fixed this by downloading the latest release

**Comment by godbout** [comment]
> the workflow doesn't work for some reason and there's a warning popup every time I try to 'ww' on alfred.
> 
> <img alt="Screenshot_2023-08-06-18_52_07_iX8tn0" width="453" src="https://user-images.githubusercontent.com/83625480/258672285-8ea2fc02-92d8-431c-b9c8-0809f6021894.png">

that means that the Workflow's binary hasn't been signed and notarized. probably you're using the transitionary release that was made to add the Workflow to the Alfred Gallery. download manually the latest version and it should be fine: https://github.com/godbout/WooshyWindowToTheForeground/releases/tag/3.0.0

hopefully the Workflow will be integrated into the Alfred Gallery, so that all future updates will happen directly from within Alfred. made a request end of June but still not approved.

**Comment by godbout** [comment]
now in Alfred Gallery.
