### ISSUE TITLE
This made my M3 Mac Super Mega Ultra Plus Blow Up! 

### ISSUE THREAD

**Issue by rkabrick** [godbout/WooshyWindowToTheForeground#7]
Between this and kindaVim, my mouse and I have realized we've grown apart. I'm leaving her next week after we finalize the paperwork. She'll get custody of our mice pups but I can visit on weekends. 

Jk. I just wanted to say you quickly became one of my favorite developers and inspired me to start messing around with Swift. I am waiting for Wooshy with bated breath as the demos make me feel all tingly inside. 

Keep up the good work!

**Comment by godbout** [comment]
thank you but i have a girlfriend 🙄️

**Comment by godbout** [comment]
> Between this and kindaVim, my mouse and I have realized we've grown apart. I'm leaving her next week after we finalize the paperwork. She'll get custody of our mice pups but I can visit on weekends.

HHAHHAHAHAHHAHHAHAHAHHA MICE. i mean, nice.

> Jk. I just wanted to say you quickly became one of my favorite developers and inspired me to start messing around with Swift. I am waiting for Wooshy with bated breath as the demos make me feel all tingly inside.

thank you! well i'm not gonna lie, i build stuff for my own self first. and mostly only if i'm having a blast. (when you own your time it's quite easy to have a blast actually.) then i share it with others and THIS IS GREAT to see people tagging along and seeing kV or the rest make their days a little better.

> Keep up the good work!

always. thanks again for taking the time to let me know!

**Comment by godbout** [comment]
> This made my M3 Mac Super Mega Ultra Plus Blow Up!

wait btw i feel i've mentioned something about that somewhere but i don't remember when and where 😅️

**Comment by rkabrick** [comment]
Lol, do you plan on open-sourcing Wooshy? 

Also, do you have any thoughts on having this workflow list open browsers and then listing tabs inside of browsers? Or will the workflow be used for bringing the browser to the foreground, and then Wooshy to pick the tab?

**Comment by godbout** [comment]
> Lol, do you plan on open-sourcing Wooshy?

nope, no open source for Wooshy. the open source period of kV has been a fiasco. i was spending more time and energy answering people who couldn't compile the source even though i made it clear i wouldn't do OSS support. Wooshy will be the same "coffee a month" price, closed source. sad. ☹️ and greedy. 🤑️

> Also, do you have any thoughts on having this workflow list open browsers and then listing tabs inside of browsers? Or will the workflow be used for bringing the browser to the foreground, and then Wooshy to pick the tab?

i did have thoughts about this. i actually deliberately made Wooshy: Window to the Foreground! (i'm starting to regret that name...) as straightforward as possible: you just bring windows to the front. actually most of the time you shouldn't even need it. you can use Alfred to call an app and it brings it forward. the issue is that when you have several windows of a same app, or windows without app (system windows), or some weird ones like in Sublime Text. so basically Wooshy: Window to the Foreground! (fucking hell) is supposed to be used for those cases where you really had to pick the (now estranged) mouse as the last ultime solution. 

for what you're asking, there's been some other solutions:
* https://github.com/mandrigin/AlfredSwitchWindows (a bit slower but still fast)
* https://contexts.co (paid app)

for me personally i've remapped macOS tabs navigation with `shift command j/k`, so i navigate tabs through those keys. faster than searching through Alfred (again, for me). (then i also have `shift command h/l` for back/forward. kinda using my Vim muscle memory here.)

**Comment by godbout** [comment]
i'm gonna add those stuff above in the README, as alternatives. cool. thanks for the idea.

also, new update of Wooshy: Window to the Foreground! (😭️). feels like i'm doing hourly builds LOL. but should be done for a while. next update will be integrating an updater from within the Workflow, but i need to rewrite https://github.com/godbout/AlfredWorkflowUpdater, so it'll come a bit later.

**Comment by rkabrick** [comment]
Ah that's too bad but I get it. Would you be opposed to a pricing model like the Agenda App for Wooshy? They charge a higher premium and that buys you 1 year of updates but you don't lose access to those updated features after the year... You just pay again if they add features you want in the year after that. I like this approach because it encourages future development like a subscription while not omitting the idea of 'ownership' from users. I have an issue with subscription-only apps that you lose access to features after you don't pay... with that being said I have 0 problem supporting good devs (ie. you). 

I have compiled kV from source and I definitely had issues but like you said in your README, you won't be helping with that so I didn't bother you. I completely get your frustration with those who disregarded your statement. 

For kV specifically, I think having the app provide basic motions and then having in-app purchases for different verbs / objects (ie. 2.99 for `d` enables delete actions) wouldn't be a terrible idea. Of course, it's your work and you have every right to price it how you see fit, this is just merely an idea. 

I'd love the opportunity to TestFlight wooshy if that ends up becoming possible. In any event, keep up the good work and I appreciate you responding at all :)

**Comment by godbout** [comment]
> Ah that's too bad but I get it. Would you be opposed to a pricing model like the Agenda App for Wooshy? They charge a higher premium and that buys you 1 year of updates but you don't lose access to those updated features after the year... You just pay again if they add features you want in the year after that. I like this approach because it encourages future development like a subscription while not omitting the idea of 'ownership' from users. I have an issue with subscription-only apps that you lose access to features after you don't pay... with that being said I have 0 problem supporting good devs (ie. you).

it's not that i'm "opposed" per se. but it's a lot of work that i'm absolutely not interested in. honestly as a user of apps the first time i saw that model it took me 10 days to get it. wait, a lifetime license but one year of update? wtf is this. i don't know. still feels overly complicated to me. need to use time and energy to make "calculations" of what's the best deal or whatever. every year thinking whether i want the updates or not etc. probably it's just me. i like "payments as a service" feel. like if kV for example makes my life better when i use my computer, a coffee a month is peanut. hell, i pay for one coffee a day to spend an hour in a bookshop reading. USD$3 for one hour of nice time, reading, learning, digesting, preparing myself to start the day. best investment ever. 

also kV and Wooshy are not sandboxed app. they have to access other apps, which means A LOT of problems. if you just deal with your own app and sanbox like the Agenda app, you're much safer. kV and Wooshy by their nature means constant breaks with other apps. also because they go deep within macOS APIs that means massive stuff to handle during new macOS versions every year. (that being said Wooshy is simpler than kV, kV is a mastodon. 5k+ test suite.)

there's a reason there's nothing close to kV out there. it's an insane amount of research (on macOS APIs, Vim, apps to handle) and implementation. took 1.5 years 7 days a week before the release (still 7 days a week since then 😂️). ultimately it's up to anyone to decide whether the price is worth to them, for what kV (or Wooshy) brings them. i own the consequence on my side. i'm not complaining about the lack of subscribers. 

also charging means responsibilities. for free open-source i don't care, i don't owe anyone anything. but for paid customers i do. if the weight is more than what it brings me, then i know myself enough to know i'll completely lose motivation. i have no interest in grinding.

what i can tell you though (i need to add this on a FAQ. FAQs are in the plans) is that before dying my apps will go open source and free. if one day i decide to stop developing them, they'll go open source and free. and price will not go up (as long as Paddle keeps the same fees of 50cents + 5%).

> I have compiled kV from source and I definitely had issues but like you said in your README, you won't be helping with that so I didn't bother you. I completely get your frustration with those who disregarded your statement.

my character didn't help. i think people have the right to ask, and i don't assume in advance whether they have seen the README or not, so i would still answer that i don't do OSS support, and i would refer them to other open/free solutions. but i think except one or two people, all the others basically told me the other apps didn't work as well, they wanted to use kV. that's when i would drop the conversations. by closing the source, i am able now ignore the requests guilt-free 😎️🚬️

> For kV specifically, I think having the app provide basic motions and then having in-app purchases for different verbs / objects (ie. 2.99 for `d` enables delete actions) wouldn't be a terrible idea. Of course, it's your work and you have every right to price it how you see fit, this is just merely an idea.

yeah i thought about this also before. like you have Visual Mode only if you pay the coffee, etc. ultimately it makes everything more complicated for me. and really i have no interest implementing those kind of things 😂️ even a good blocking system. so i came up with the "sleeping time". may not be the best but it's fun.

clearly from all the feedback i got, people prefer the things you mention rather than the sub. i understand, but i just don't "get" it. for me a sub is so easy to compute. "this costs 3$ a month. is what this thing brings me worth 3$ a month?" the answer to that question is so clear for me. but a buying price + years of updates +/- in app etc etc, i don't know. it melts my brains. but again definitely the feedback tells me i'm not mainstream.

> I'd love the opportunity to TestFlight wooshy if that ends up becoming possible.

yes. Wooshy a1 should be coming out this week. one big feature will be missing at first, and you may need the Accessibility Inspector to know what to type to match images, icons, etc. that feature will come before the beta, but it's a big one. so i need time. but the alpha is already very usable. i'm having a lot of fun with it :D

> and I appreciate you responding at all :)

of course. that's the whole point of staying small. direct contact. nothing better.

**Comment by godbout** [comment]
Wooshy a1 is out! https://wooshy.app
